const users = [
  {
    id: 0,
    created_at: "03.06.2023",
    name: "Chatman",
    avatar: "https://eu.ui-avatars.com/api/?name=Chat+Gram&size=250",
    last_message: "Chatman Web was updated.",
    unread_count: 1,
    last_message_time: "20:10",
  },
  {
    id: 1,
    created_at: "03.06.2023",
    name: "Jessica Drew",
    avatar:
      "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
    last_message: "Ok, see you later",
    unread_count: 2,
    last_message_time: "19:10",
  },
  {
    id: 2,
    created_at: "03.06.2023",
    name: "David Moore",
    avatar: "https://eu.ui-avatars.com/api/?name=A&size=250",
    last_message: "You: i don't remember anything 😄 ",
    unread_count: 1,
    last_message_time: "18:10",
  },
  {
    id: 3,
    created_at: "03.06.2023",
    name: "Greg James",
    avatar:
      "https://avatars.dicebear.com/api/adventurer-neutral/mail%40ashallendesign.co.uk.svg",
    last_message: "I got a job at SpaceX 🎉 🚀  ",
    last_message_time: "18:10",
    unread_count: 0,
  },
  {
    id: 4,
    created_at: "03.06.2023",
    name: "Emily Dorson",
    avatar: "https://picsum.photos/id/90/200/300",
    last_message: "Table for four, 5PM. Be there.",
    unread_count: 0,
    last_message_time: "17:10",
  },
  {
    id: 5,
    created_at: "03.05.2023",
    name: "Office Chat",
    avatar: "https://picsum.photos/id/82/200/300",
    last_message: "Lewis: All done mate 😆  ",
    unread_count: 0,
    last_message_time: "12:20",
  },
  {
    id: 6,
    created_at: "29.05.2023",
    name: "Little Sister",
    avatar: "https://picsum.photos/id/83/200/300",
    last_message: "Tell mom i will be home for tea 💜 ",
    unread_count: 0,
    last_message_time: "11:10",
  },
  {
    id: 7,
    created_at: "27.05.2023",
    name: "Art Class",
    avatar: "https://picsum.photos/id/84/200/300",
    last_message: "",
    unread_count: 0,
    last_message_time: "08:10",
  },
  {
    id: 8,
    created_at: "28.05.2023",
    name: "Jennifer Lawrence",
    avatar: "https://picsum.photos/id/85/200/300",
    last_message: "",
    unread_count: 0,
    last_message_time: "Mon",
  },
  {
    id: 9,
    created_at: "28.05.2023",
    name: "Jason Roy",
    avatar: "https://picsum.photos/id/55/200/300",
    last_message: "",
    unread_count: 0,
    last_message_time: "Wed",
  },
  {
    id: 10,
    created_at: "28.05.2023",
    name: "+91 123456789",
    avatar: "https://picsum.photos/id/87/200/300",
    last_message: "",
    unread_count: 0,
    last_message_time: "Tue",
  },
];

export default users;
